### ISSUE TITLE
Conf-based vs Factory

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/jump-template#1]
It seems that if we have our objects defined as configuration objects (data in a text file), that would eliminate the need for the Object Factory class you have. 

Meaning the factory would just turn into a parser that takes in a conf object and builds it based on the components defined in the conf.

(If we get to that point.... 'tis gunna be sweeeeeet)

**Comment by Kenoshen** [comment]
Ya, I was literally just now looking at that factory class and thinking the same thing.  I think I'm ready to start trying to configurize it all.  We will see how it goes.  I'll maybe make a PR for that one so that it is a little more visible.

**Comment by MondayHopscotch** [comment]
If you're planning on working on things tonight - I may be down for doing a hangout and chatting and stuff. I'll probably be working on cleaning up a couple other things in Jump tonight because I have some free time to blow.

**Comment by Kenoshen** [comment]
I'll be on tonight around 6ish if not before.  I'm down for a hangout.

**Comment by MondayHopscotch** [comment]
It's a date. <3 (I'll be getting home around 6 or so. I'll hit you up when
I am online)

On Thu, Sep 22, 2016 at 2:25 PM, Michael Wingfield <notifications@github.com
