### ISSUE TITLE
Idea regarding dynamic conf loading

### ISSUE THREAD

**Issue by MondayHopscotch** [bitDecayGames/jump-template#3]
Currently, there is a constructor that has all properties defined as arguments to it. Do we really need this? If we are generating components via conf objects, the `Constructor(MyGameObject, Conf)` seems like it should be all we need.

Am I missing something with why we have the non-conf constructor?

**Comment by Kenoshen** [comment]
Maybe we don't need it.  But without it you have no way to define an object in code.  Like you said though, with the conf-based objs we probably don't want that anyways.  I'll make it a private constructor for now and that way it can't be used in code but it still is there if we want/need it in the future.

**Comment by MondayHopscotch** [comment]
My thoughts led me to wondering if you could do things such as reflection. So when loading from config, it would just put each config value onto a field on the component. If it finds a field that doesn't have a config element for it, it throws an error.

(This is sort of a rant. I don't think we actually need this, but the thought crossed my mind, so I figured I'd write it down. I think what you have right now is going to work well for us)

**Comment by Kenoshen** [comment]
You make a good point though...

**Comment by MondayHopscotch** [comment]
We should worry about it once we actually start building the game and have a better feel for what works better :) But I'm getting more and more stoked to keep going on this.

**Comment by MondayHopscotch** [comment]
(also -- kudos on all the stuff you've gotten done so far. Just for giggles I looked at how much you've done in this project and there's almost 3000 lines of just code in here)
